export const routes = {
  HOME: "/",
  LOGIN: "/login",
  SIGN_UP: "/signup",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  SUBSCRIPTION: "/subscription",
  SUBSCRIPTIONS: "/subscriptions",
  INVOICES: "/invoices",
  PROFILE: "/profile",
  SETTINGS: "/settings",
  CHECK_OUT: "/checkout",
  ADMIN: "/admin",
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_VOICE_NOTES: "/admin/voice-notes",
  ADMIN_USERS: "/admin/users",
  ADMIN_SETTINGS: "/admin/settings",
  ADMIN_PROFILE: "/admin/profile",
};
